import AsyncStorage from '@react-native-async-storage/async-storage';
import * as SecureStore from 'expo-secure-store';

export type IdempotentOperation =
  | 'reserve_add'
  | 'bill_create'
  | 'income_create'
  | 'recurring_template_create';

export interface PendingOperation {
  key: string;
  originalPayload: Record<string, unknown>;
  canonicalPayload: string;
  logicalFingerprint: string;
  createdAt: number;
  state: 'pending';
}

export interface MutationSessionSnapshot {
  userId: string;
  accessToken: string;
  generation: number;
}

export interface PreparedPendingMutation extends PendingOperation {
  ownerId: string;
  accessToken: string;
  sessionGeneration: number;
}

const LOCAL_RETENTION_MS = 90 * 24 * 60 * 60 * 1000;
const OPERATIONS: IdempotentOperation[] = [
  'reserve_add',
  'bill_create',
  'income_create',
  'recurring_template_create',
];
const storeQueues = new Map<string, Promise<void>>();

const normalizeValue = (value: unknown): unknown => {
  if (Array.isArray(value)) return value.map(normalizeValue);
  if (value && typeof value === 'object') {
    return Object.keys(value as Record<string, unknown>)
      .sort()
      .reduce<Record<string, unknown>>((result, key) => {
        result[key] = normalizeValue((value as Record<string, unknown>)[key]);
        return result;
      }, {});
  }
  return value;
};

export const canonicalMutationPayload = (payload: Record<string, unknown>) =>
  JSON.stringify(normalizeValue(payload));

/**
 * Local logical-intent identity is deliberately narrower than the transport payload.
 * Income `date` is generated by the UI from the financial calendar at first submit,
 * so it must not manufacture a new intent when a retry crosses local midnight.
 * The original complete payload is still persisted and replayed unchanged.
 */
export const logicalMutationPayload = (
  operation: IdempotentOperation,
  payload: Record<string, unknown>,
): Record<string, unknown> => {
  if (operation !== 'income_create') return payload;
  const { date: _derivedDate, ...logical } = payload;
  return logical;
};

const ownerToken = (ownerId: string) => {
  const trimmed = ownerId.trim();
  if (!trimmed) throw new Error('Authenticated owner is required for financial mutations.');
  return encodeURIComponent(trimmed);
};

const legacyPendingStorageKey = (ownerId: string, operation: IdempotentOperation) =>
  `@financeflow:idempotency:${ownerToken(ownerId)}:${operation}`;

export const pendingMutationStorageKey = (ownerId: string, operation: IdempotentOperation) =>
  `@financeflow:idempotency-secure:v2:${ownerToken(ownerId)}:${operation}`;

const newOperationKey = () => {
  const randomPart = Math.random().toString(36).slice(2, 14);
  return `ff_${Date.now().toString(36)}_${randomPart}`;
};

const parsePayload = (value: unknown): Record<string, unknown> | null => {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null;
  return value as Record<string, unknown>;
};

const normalizePendingRecord = (
  item: unknown,
  operation: IdempotentOperation,
): PendingOperation | null => {
  if (!item || typeof item !== 'object') return null;
  const candidate = item as Partial<PendingOperation> & { canonicalPayload?: unknown };
  if (
    typeof candidate.key !== 'string'
    || typeof candidate.createdAt !== 'number'
    || !Number.isFinite(candidate.createdAt)
  ) {
    return null;
  }

  let originalPayload = parsePayload(candidate.originalPayload);
  if (!originalPayload && typeof candidate.canonicalPayload === 'string') {
    try {
      originalPayload = parsePayload(JSON.parse(candidate.canonicalPayload));
    } catch {
      originalPayload = null;
    }
  }
  if (!originalPayload) return null;

  const canonicalPayload = canonicalMutationPayload(originalPayload);
  const logicalFingerprint = canonicalMutationPayload(
    logicalMutationPayload(operation, originalPayload),
  );
  return {
    key: candidate.key,
    originalPayload,
    canonicalPayload,
    logicalFingerprint,
    createdAt: candidate.createdAt,
    state: 'pending',
  };
};

const writePendingUnlocked = async (
  ownerId: string,
  operation: IdempotentOperation,
  operations: PendingOperation[],
) => {
  const storageKey = pendingMutationStorageKey(ownerId, operation);
  if (operations.length === 0) {
    await SecureStore.deleteItemAsync(storageKey);
    return;
  }
  await SecureStore.setItemAsync(storageKey, JSON.stringify(operations));
};

const readPendingUnlocked = async (
  ownerId: string,
  operation: IdempotentOperation,
): Promise<PendingOperation[]> => {
  const secureKey = pendingMutationStorageKey(ownerId, operation);
  const legacyKey = legacyPendingStorageKey(ownerId, operation);
  let raw = await SecureStore.getItemAsync(secureKey);
  let fromLegacy = false;

  if (raw === null) {
    raw = await AsyncStorage.getItem(legacyKey);
    fromLegacy = raw !== null;
  }
  if (!raw) {
    if (fromLegacy) await AsyncStorage.removeItem(legacyKey);
    return [];
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    parsed = [];
  }

  const cutoff = Date.now() - LOCAL_RETENTION_MS;
  const normalized = Array.isArray(parsed)
    ? parsed
      .map((item) => normalizePendingRecord(item, operation))
      .filter((item): item is PendingOperation => Boolean(item && item.createdAt >= cutoff))
    : [];

  if (fromLegacy) {
    await writePendingUnlocked(ownerId, operation, normalized);
    await AsyncStorage.removeItem(legacyKey);
  } else if (JSON.stringify(parsed) !== JSON.stringify(normalized)) {
    await writePendingUnlocked(ownerId, operation, normalized);
  }

  return normalized;
};

const withStoreLock = async <T>(
  ownerId: string,
  operation: IdempotentOperation,
  task: () => Promise<T>,
): Promise<T> => {
  const storageKey = pendingMutationStorageKey(ownerId, operation);
  const previous = storeQueues.get(storageKey) ?? Promise.resolve();
  let release!: () => void;
  const gate = new Promise<void>((resolve) => { release = resolve; });
  const queued = previous.catch(() => undefined).then(() => gate);
  storeQueues.set(storageKey, queued);

  await previous.catch(() => undefined);
  try {
    return await task();
  } finally {
    release();
    if (storeQueues.get(storageKey) === queued) {
      storeQueues.delete(storageKey);
    }
  }
};

export const getOrCreatePendingOperation = async (
  ownerId: string,
  operation: IdempotentOperation,
  payload: Record<string, unknown>,
): Promise<PendingOperation> => withStoreLock(ownerId, operation, async () => {
  const logicalFingerprint = canonicalMutationPayload(logicalMutationPayload(operation, payload));
  const pending = await readPendingUnlocked(ownerId, operation);
  const existing = pending.find((item) => item.logicalFingerprint === logicalFingerprint);
  if (existing) return existing;

  const originalPayload = JSON.parse(canonicalMutationPayload(payload)) as Record<string, unknown>;
  const created: PendingOperation = {
    key: newOperationKey(),
    originalPayload,
    canonicalPayload: canonicalMutationPayload(originalPayload),
    logicalFingerprint,
    createdAt: Date.now(),
    state: 'pending',
  };
  await writePendingUnlocked(ownerId, operation, [...pending, created]);
  return created;
});

export const clearPendingOperation = async (
  ownerId: string,
  operation: IdempotentOperation,
  key: string,
) => withStoreLock(ownerId, operation, async () => {
  const pending = await readPendingUnlocked(ownerId, operation);
  await writePendingUnlocked(
    ownerId,
    operation,
    pending.filter((item) => item.key !== key),
  );
});

export const preparePendingMutation = async (
  snapshot: MutationSessionSnapshot,
  operation: IdempotentOperation,
  payload: Record<string, unknown>,
  isSessionCurrent: (snapshot: MutationSessionSnapshot) => Promise<boolean> | boolean,
): Promise<PreparedPendingMutation> => {
  const pending = await getOrCreatePendingOperation(snapshot.userId, operation, payload);
  if (!(await isSessionCurrent(snapshot))) {
    throw new Error('Authenticated session changed while preparing a financial mutation.');
  }
  return {
    ...pending,
    ownerId: snapshot.userId,
    accessToken: snapshot.accessToken,
    sessionGeneration: snapshot.generation,
  };
};

const isDefinitiveClientRejection = (error: any) => {
  const status = Number(error?.response?.status || 0);
  if (status < 400 || status >= 500) return false;
  return status !== 408 && status !== 425 && status !== 429;
};

export const runIdempotentMutation = async <T>(
  ownerId: string,
  operation: IdempotentOperation,
  payload: Record<string, unknown>,
  request: (idempotencyKey: string, originalPayload: Record<string, unknown>) => Promise<T>,
): Promise<T> => {
  const pending = await getOrCreatePendingOperation(ownerId, operation, payload);
  try {
    const result = await request(pending.key, pending.originalPayload);
    await clearPendingOperation(ownerId, operation, pending.key);
    return result;
  } catch (error) {
    if (isDefinitiveClientRejection(error)) {
      await clearPendingOperation(ownerId, operation, pending.key);
    }
    throw error;
  }
};

export const purgePendingOperationsForOwner = async (ownerId: string) => {
  for (const operation of OPERATIONS) {
    await withStoreLock(ownerId, operation, async () => {
      await SecureStore.deleteItemAsync(pendingMutationStorageKey(ownerId, operation));
      await AsyncStorage.removeItem(legacyPendingStorageKey(ownerId, operation));
    });
  }
};
